nameOverride: ''
fullnameOverride: ''
plugin:
  enabled: true
  versionOverride: ''
  endpoint: >-
    https://raw.githubusercontent.com/scelios/showEvent/master/extensions/showevent/0.1.1
  compressedEndpoint: >-
    https://raw.githubusercontent.com/scelios/showEvent/master/extensions/showevent/0.1.1.tgz
  noCache: false
  noAuth: false
  metadata: {}
