default:
  tags:
   - k8sv3
   - mtMC
   - stg
  image:
      name: jfrog-artifactory.steelhome.internal/docker/node:22.17.0
variables:
  NODE_OPTIONS: "--max-old-space-size=1536"
  KUBERNETES_CPU_REQUEST: 300m
  KUBERNETES_CPU_LIMIT: 2000m
  KUBERNETES_MEMORY_REQUEST: 512Mi
  KUBERNETES_MEMORY_LIMIT: 2Gi
  FORCE_RUN_AS: master

include:
  - project: "mtmc/projects/it-factory/piplib"
    ref: develop
    file: "/pipelines/npm/npm.gitlab-ci.yml"


build:
  needs: ["prepare"]
  before_script:
  - yarn cache clean 
  - rm -rf node_modules 
  - yarn install
  - wget https://github.com/jqlang/jq/releases/download/jq-1.8.1/jq-linux-amd64 -O /usr/local/bin/jq && chmod +x /usr/local/bin/jq
  - wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq && chmod +x /usr/local/bin/yq
  - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  artifacts:
    untracked: false
    when: on_success
    access: all
    expire_in: 30 days
    paths:
    - tmp


package-chart:
  rules: 
    - when: never