nameOverride: ''
fullnameOverride: ''
plugin:
  enabled: true
  versionOverride: ''
  endpoint: >-
    https://raw.githubusercontent.com/scelios/showEvent/master/extensions/profilepictures/0.1.0
  compressedEndpoint: >-
    https://raw.githubusercontent.com/scelios/showEvent/master/extensions/profilepictures/0.1.0.tgz
  noCache: false
  noAuth: false
  metadata: {}
